apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: minio
  labels:
    app: minio
stringData:
  MINIO_ROOT_USER: "{{ .Values.user.accessKey }}"
  MINIO_ROOT_PASSWORD: "{{ .Values.user.secretAccessKey }}"
